name: Build Website

on:
  push:
  pull_request:

jobs:
  build:
    uses: bash/satellite/.github/workflows/build-reusable.yml@v1
    with:
      workflow-ref: v1
    permissions:
      pages: write
      id-token: write
